### ISSUE TITLE
closing flashbot reply body: context canceled

### ISSUE THREAD

**Issue by joleeee** [cryptoriums/flashbot#4]
When trying to use CallBundle and SendBundle, i get `flashbot call request: closing flashbot reply body: context canceled`. It seem like it sometimes works but it's rare and usually fails again after one call. Is this a known issue? It seems some github action is failing with the same error: https://github.com/cryptoriums/flashbot/runs/4172081239

I get this on both goerli and mainnet. Maybe it's a problem with relay.flashbots.net?

**Comment by krasi-georgiev** [comment]
I am also puzzled by this one and can't figure it out yet, tried increasing the client timeout to 5 seconds, but with no joy.

**Comment by skateboard** [comment]
Ya i get the same issue

**Comment by skateboard** [comment]
and this action is successful? https://github.com/cryptoriums/flashbot/runs/4197352614

**Comment by krasi-georgiev** [comment]
yes because I pinned the GH action to 1.17.2, 
it is related to this upstream golang bug so you just need to use golang 1.17.2 for now
https://github.com/golang/go/issues/49366

closing now, but feel free to reopen if anything is unlcear.
